services:
  v2-runtime:
    restart: unless-stopped

  otel-collector:
    ports: !reset []
    networks:
      - default
      - observability
    restart: unless-stopped

networks:
  observability:
    external: true
