#!/bin/sh
set -eu

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
REPO_ROOT=$(CDPATH= cd -- "$SCRIPT_DIR/.." && pwd)
DEFAULT_PROJECT_HOST_PATH="${AGENTIC_MESH_PROJECT_HOST_PATH:-$REPO_ROOT/examples/projects/agentic-mesh-dev}"
COMPOSE_SRC="${AGENTIC_MESH_COMPOSE_SRC:-$DEFAULT_PROJECT_HOST_PATH/deploy/compose}"
COMPOSE_FILE_NAME="${AGENTIC_MESH_COMPOSE_FILE_NAME:-docker-compose.v4.yml}"
STAGE_DIR="${AGENTIC_MESH_COMPOSE_STAGE_DIR:-$HOME/agentic-mesh-compose-run}"
PARENT_WORKSPACE_HOST_PATH="${AGENTIC_MESH_WORKSPACE_HOST_PATH:-}"
PARENT_RUNTIME_BUILD_CONTEXT="${AGENTIC_MESH_RUNTIME_BUILD_CONTEXT:-}"
PARENT_SYSTEM_HOST_PATH="${AGENTIC_MESH_SYSTEM_HOST_PATH:-}"
PARENT_PROJECT_HOST_PATH="${AGENTIC_MESH_PROJECT_HOST_PATH:-}"
PARENT_DOCUMENTS_HOST_PATH="${AGENTIC_MESH_DOCUMENTS_HOST_PATH:-}"

if [ -f "$COMPOSE_SRC/.env" ]; then
  set -a
  # shellcheck disable=SC1091
  . "$COMPOSE_SRC/.env"
  set +a
fi

if [ "${AGENTIC_MESH_PREFER_PARENT_PATHS:-}" = "1" ]; then
  [ -n "$PARENT_WORKSPACE_HOST_PATH" ] && AGENTIC_MESH_WORKSPACE_HOST_PATH="$PARENT_WORKSPACE_HOST_PATH"
  [ -n "$PARENT_RUNTIME_BUILD_CONTEXT" ] && AGENTIC_MESH_RUNTIME_BUILD_CONTEXT="$PARENT_RUNTIME_BUILD_CONTEXT"
  [ -n "$PARENT_SYSTEM_HOST_PATH" ] && AGENTIC_MESH_SYSTEM_HOST_PATH="$PARENT_SYSTEM_HOST_PATH"
  [ -n "$PARENT_PROJECT_HOST_PATH" ] && AGENTIC_MESH_PROJECT_HOST_PATH="$PARENT_PROJECT_HOST_PATH"
  [ -n "$PARENT_DOCUMENTS_HOST_PATH" ] && AGENTIC_MESH_DOCUMENTS_HOST_PATH="$PARENT_DOCUMENTS_HOST_PATH"
fi

AGENTIC_MESH_URL_ROOT="${AGENTIC_MESH_URL_ROOT:-http://linuxch:8100}"
AGENTIC_MESH_RUNTIME_BUILD_CONTEXT="${AGENTIC_MESH_RUNTIME_BUILD_CONTEXT:-$REPO_ROOT}"
AGENTIC_MESH_SYSTEM_HOST_PATH="${AGENTIC_MESH_SYSTEM_HOST_PATH:-$REPO_ROOT}"
AGENTIC_MESH_PROJECT_HOST_PATH="${AGENTIC_MESH_PROJECT_HOST_PATH:-$DEFAULT_PROJECT_HOST_PATH}"
AGENTIC_MESH_WORKSPACE_HOST_PATH="${AGENTIC_MESH_WORKSPACE_HOST_PATH:-$AGENTIC_MESH_PROJECT_HOST_PATH/target-repos/agentic-mesh}"
AGENTIC_MESH_DOCUMENTS_HOST_PATH="${AGENTIC_MESH_DOCUMENTS_HOST_PATH:-$AGENTIC_MESH_PROJECT_HOST_PATH/documents}"
AGENTIC_MESH_CODEX_HOME_HOST_PATH="${AGENTIC_MESH_CODEX_HOME_HOST_PATH:-$AGENTIC_MESH_PROJECT_HOST_PATH/state/worker_mounts/codex-agentic-mesh-dev-team-home-q}"
AGENTIC_MESH_OTEL_COLLECTOR_CONFIG_HOST_PATH="${AGENTIC_MESH_OTEL_COLLECTOR_CONFIG_HOST_PATH:-$REPO_ROOT/config/otel/collector.yaml}"
AGENTIC_MESH_RESTRICTED_SAFE_OUTPUT_CONFIG_HOST_PATH="$AGENTIC_MESH_PROJECT_HOST_PATH/deploy/codex/restricted-safe-output-config.toml"
AGENTIC_MESH_IMAGE_TAG="${AGENTIC_MESH_IMAGE_TAG:-agentic-mesh:local}"
AGENTIC_MESH_BASE_IMAGE_TAG="${AGENTIC_MESH_BASE_IMAGE_TAG:-agentic-mesh:base-agent}"
AGENTIC_MESH_OPS_IMAGE_TAG="${AGENTIC_MESH_OPS_IMAGE_TAG:-agentic-mesh:ops-agent}"
AGENTIC_MESH_DEV_IMAGE_TAG="${AGENTIC_MESH_DEV_IMAGE_TAG:-agentic-mesh:dev-agent}"
AGENTIC_MESH_QA_IMAGE_TAG="${AGENTIC_MESH_QA_IMAGE_TAG:-agentic-mesh:qa-agent}"
AGENTIC_MESH_ONEDRIVE_TOKEN="${AGENTIC_MESH_ONEDRIVE_TOKEN:-}"
AGENTIC_MESH_ONEDRIVE_DRIVE_ID="${AGENTIC_MESH_ONEDRIVE_DRIVE_ID:-}"
AGENTIC_MESH_GRAPH_CLIENT_ID="${AGENTIC_MESH_GRAPH_CLIENT_ID:-}"
AGENTIC_MESH_GRAPH_TENANT_ID="${AGENTIC_MESH_GRAPH_TENANT_ID:-}"
AGENTIC_MESH_GRAPH_REFRESH_TOKEN="${AGENTIC_MESH_GRAPH_REFRESH_TOKEN:-}"
AGENTIC_MESH_GRAPH_SCOPES="${AGENTIC_MESH_GRAPH_SCOPES:-}"
AGENTIC_MESH_SPONSOR_TEAMS_USER_ID="${AGENTIC_MESH_SPONSOR_TEAMS_USER_ID:-}"
AGENTIC_MESH_TEAMS_TOKEN="${AGENTIC_MESH_TEAMS_TOKEN:-}"
AGENTIC_MESH_TEAMS_SENDER_USER_ID="${AGENTIC_MESH_TEAMS_SENDER_USER_ID:-}"
AGENTIC_MESH_TEAMS_PUBLIC_ENDPOINT="${AGENTIC_MESH_TEAMS_PUBLIC_ENDPOINT:-}"
AGENTIC_MESH_TEAMS_BOT_SERVICE_URL="${AGENTIC_MESH_TEAMS_BOT_SERVICE_URL:-}"
AGENTIC_MESH_TENANT_ID="${AGENTIC_MESH_TENANT_ID:-}"
AGENTIC_MESH_PROJECT_TEAM_ID="${AGENTIC_MESH_PROJECT_TEAM_ID:-}"
AGENTIC_MESH_PROJECT_CHANNEL_ID="${AGENTIC_MESH_PROJECT_CHANNEL_ID:-}"
AGENTIC_MESH_SPONSOR_AAD_OBJECT_ID="${AGENTIC_MESH_SPONSOR_AAD_OBJECT_ID:-}"
TEAMS_BOT_BUSINESS_ANALYST_APP_ID="${TEAMS_BOT_BUSINESS_ANALYST_APP_ID:-}"
TEAMS_BOT_BUSINESS_ANALYST_SECRET="${TEAMS_BOT_BUSINESS_ANALYST_SECRET:-}"
TEAMS_BOT_DELIVERY_MANAGER_APP_ID="${TEAMS_BOT_DELIVERY_MANAGER_APP_ID:-}"
TEAMS_BOT_DELIVERY_MANAGER_SECRET="${TEAMS_BOT_DELIVERY_MANAGER_SECRET:-}"
TEAMS_BOT_ENTERPRISE_ARCHITECT_APP_ID="${TEAMS_BOT_ENTERPRISE_ARCHITECT_APP_ID:-}"
TEAMS_BOT_ENTERPRISE_ARCHITECT_SECRET="${TEAMS_BOT_ENTERPRISE_ARCHITECT_SECRET:-}"
TEAMS_BOT_PLATFORM_ENGINEER_APP_ID="${TEAMS_BOT_PLATFORM_ENGINEER_APP_ID:-}"
TEAMS_BOT_PLATFORM_ENGINEER_SECRET="${TEAMS_BOT_PLATFORM_ENGINEER_SECRET:-}"
TEAMS_BOT_PRODUCT_MANAGER_APP_ID="${TEAMS_BOT_PRODUCT_MANAGER_APP_ID:-}"
TEAMS_BOT_PRODUCT_MANAGER_SECRET="${TEAMS_BOT_PRODUCT_MANAGER_SECRET:-}"
TEAMS_BOT_PROMPT_ENGINEER_APP_ID="${TEAMS_BOT_PROMPT_ENGINEER_APP_ID:-}"
TEAMS_BOT_PROMPT_ENGINEER_SECRET="${TEAMS_BOT_PROMPT_ENGINEER_SECRET:-}"
TEAMS_BOT_PROJECT_MANAGER_APP_ID="${TEAMS_BOT_PROJECT_MANAGER_APP_ID:-}"
TEAMS_BOT_PROJECT_MANAGER_SECRET="${TEAMS_BOT_PROJECT_MANAGER_SECRET:-}"
TEAMS_BOT_RESEARCH_ANALYST_APP_ID="${TEAMS_BOT_RESEARCH_ANALYST_APP_ID:-}"
TEAMS_BOT_RESEARCH_ANALYST_SECRET="${TEAMS_BOT_RESEARCH_ANALYST_SECRET:-}"
TEAMS_BOT_SECURITY_ARCHITECT_APP_ID="${TEAMS_BOT_SECURITY_ARCHITECT_APP_ID:-}"
TEAMS_BOT_SECURITY_ARCHITECT_SECRET="${TEAMS_BOT_SECURITY_ARCHITECT_SECRET:-}"
TEAMS_BOT_SOLUTION_ARCHITECT_APP_ID="${TEAMS_BOT_SOLUTION_ARCHITECT_APP_ID:-}"
TEAMS_BOT_SOLUTION_ARCHITECT_SECRET="${TEAMS_BOT_SOLUTION_ARCHITECT_SECRET:-}"
TEAMS_BOT_ENGINEERING_APP_ID="${TEAMS_BOT_ENGINEERING_APP_ID:-}"
TEAMS_BOT_ENGINEERING_SECRET="${TEAMS_BOT_ENGINEERING_SECRET:-}"
TEAMS_BOT_QA_ENGINEER_APP_ID="${TEAMS_BOT_QA_ENGINEER_APP_ID:-}"
TEAMS_BOT_QA_ENGINEER_SECRET="${TEAMS_BOT_QA_ENGINEER_SECRET:-}"
TEAMS_BOT_RELEASE_MANAGER_APP_ID="${TEAMS_BOT_RELEASE_MANAGER_APP_ID:-}"
TEAMS_BOT_RELEASE_MANAGER_SECRET="${TEAMS_BOT_RELEASE_MANAGER_SECRET:-}"
TEAMS_BOT_TECHNICAL_WRITER_APP_ID="${TEAMS_BOT_TECHNICAL_WRITER_APP_ID:-}"
TEAMS_BOT_TECHNICAL_WRITER_SECRET="${TEAMS_BOT_TECHNICAL_WRITER_SECRET:-}"
TEAMS_BOT_UX_DESIGNER_APP_ID="${TEAMS_BOT_UX_DESIGNER_APP_ID:-}"
TEAMS_BOT_UX_DESIGNER_SECRET="${TEAMS_BOT_UX_DESIGNER_SECRET:-}"
AGENTIC_MESH_V4_STATUS_PORT="${AGENTIC_MESH_V4_STATUS_PORT:-8100}"
AGENTIC_MESH_DATABASE_NAME="${AGENTIC_MESH_DATABASE_NAME:-agentic_mesh_v4}"
AGENTIC_MESH_DATABASE_USER="${AGENTIC_MESH_DATABASE_USER:-agentic_mesh}"
AGENTIC_MESH_DATABASE_HOST="${AGENTIC_MESH_DATABASE_HOST:-agentic-mesh-postgres}"
AGENTIC_MESH_DATABASE_PORT="${AGENTIC_MESH_DATABASE_PORT:-5432}"
AGENTIC_MESH_POSTGRES_HOST_PORT="${AGENTIC_MESH_POSTGRES_HOST_PORT:-54329}"
if [ -n "${AGENTIC_MESH_FORCE_V4_STATUS_PORT:-}" ]; then
  AGENTIC_MESH_V4_STATUS_PORT="$AGENTIC_MESH_FORCE_V4_STATUS_PORT"
fi
AGENTIC_MESH_SOURCE_COMMIT="${AGENTIC_MESH_SOURCE_COMMIT:-$(git -C "$REPO_ROOT" rev-parse --short=12 HEAD 2>/dev/null || printf 'unknown')}"
AGENTIC_MESH_SOURCE_BRANCH="${AGENTIC_MESH_SOURCE_BRANCH:-$(git -C "$REPO_ROOT" symbolic-ref --quiet --short HEAD 2>/dev/null || printf 'detached')}"
AGENTIC_MESH_BUILD_TIME="${AGENTIC_MESH_BUILD_TIME:-$(date -u '+%Y-%m-%dT%H:%M:%SZ')}"
AGENTIC_MESH_BUILD_REF="${AGENTIC_MESH_BUILD_REF:-$AGENTIC_MESH_SOURCE_BRANCH@$AGENTIC_MESH_SOURCE_COMMIT}"
AGENTIC_MESH_ENVIRONMENT="${AGENTIC_MESH_ENVIRONMENT:-dogfood}"
AGENTIC_MESH_LIFECYCLE_LOCK_PATH="${AGENTIC_MESH_LIFECYCLE_LOCK_PATH:-$AGENTIC_MESH_PROJECT_HOST_PATH/state/compose-lifecycle.lock}"
AGENTIC_MESH_LIFECYCLE_LOCK_TIMEOUT_SECONDS="${AGENTIC_MESH_LIFECYCLE_LOCK_TIMEOUT_SECONDS:-300}"
AGENTIC_MESH_LIFECYCLE_LOCK_STALE_SECONDS="${AGENTIC_MESH_LIFECYCLE_LOCK_STALE_SECONDS:-900}"
COMPOSE_PROJECT_NAME="${COMPOSE_PROJECT_NAME:-agentic-mesh}"
AGENTIC_MESH_LIFECYCLE_COMPOSE_PROJECT_NAME="${AGENTIC_MESH_LIFECYCLE_COMPOSE_PROJECT_NAME:-$COMPOSE_PROJECT_NAME}"
AGENTIC_MESH_LIFECYCLE_COMPOSE_PROFILES="${AGENTIC_MESH_LIFECYCLE_COMPOSE_PROFILES:-v4}"
AGENTIC_MESH_LIFECYCLE_WORKING_DIRECTORY="${AGENTIC_MESH_LIFECYCLE_WORKING_DIRECTORY:-/mesh/project/deploy/compose}"

reject_container_bind_path() {
  name=$1
  value=$2
  case "$value" in
    /mesh|/mesh/*|/documents|/documents/*|/workspace|/workspace/*)
      if [ "${AGENTIC_MESH_ALLOW_CONTAINER_BIND_PATHS:-}" != "1" ]; then
        printf '%s\n' "Refusing to deploy: $name is '$value', which is an in-container path, not a Docker host bind path." >&2
        printf '%s\n' "Use linuxch host paths such as /home/nich/agentic-mesh-projects/agentic-mesh-dev, or set AGENTIC_MESH_ALLOW_CONTAINER_BIND_PATHS=1 only for an explicit local-dev override." >&2
        exit 1
      fi
      ;;
  esac
}

reject_container_bind_path AGENTIC_MESH_RUNTIME_BUILD_CONTEXT "$AGENTIC_MESH_RUNTIME_BUILD_CONTEXT"
reject_container_bind_path AGENTIC_MESH_SYSTEM_HOST_PATH "$AGENTIC_MESH_SYSTEM_HOST_PATH"
reject_container_bind_path AGENTIC_MESH_PROJECT_HOST_PATH "$AGENTIC_MESH_PROJECT_HOST_PATH"
reject_container_bind_path AGENTIC_MESH_WORKSPACE_HOST_PATH "$AGENTIC_MESH_WORKSPACE_HOST_PATH"
reject_container_bind_path AGENTIC_MESH_DOCUMENTS_HOST_PATH "$AGENTIC_MESH_DOCUMENTS_HOST_PATH"
reject_container_bind_path AGENTIC_MESH_CODEX_HOME_HOST_PATH "$AGENTIC_MESH_CODEX_HOME_HOST_PATH"
reject_container_bind_path AGENTIC_MESH_OTEL_COLLECTOR_CONFIG_HOST_PATH "$AGENTIC_MESH_OTEL_COLLECTOR_CONFIG_HOST_PATH"
reject_container_bind_path AGENTIC_MESH_RESTRICTED_SAFE_OUTPUT_CONFIG_HOST_PATH "$AGENTIC_MESH_RESTRICTED_SAFE_OUTPUT_CONFIG_HOST_PATH"

require_regular_file() {
  name=$1
  value=$2
  if [ ! -f "$value" ]; then
    printf '%s\n' "Refusing to deploy: $name must exist as a regular file before Docker Compose runs: $value" >&2
    printf '%s\n' "The deployment will not allow Docker to create a directory at a required file-bind source." >&2
    exit 1
  fi
}

require_regular_file \
  AGENTIC_MESH_RESTRICTED_SAFE_OUTPUT_CONFIG_HOST_PATH \
  "$AGENTIC_MESH_RESTRICTED_SAFE_OUTPUT_CONFIG_HOST_PATH"

if [ "${AGENTIC_MESH_ALLOW_WORKSPACE_EQUALS_SYSTEM:-}" != "1" ]; then
  RESOLVED_WORKSPACE=$(mkdir -p "$AGENTIC_MESH_WORKSPACE_HOST_PATH" && cd "$AGENTIC_MESH_WORKSPACE_HOST_PATH" && pwd -P)
  RESOLVED_SYSTEM=$(cd "$AGENTIC_MESH_SYSTEM_HOST_PATH" && pwd -P)
  RESOLVED_BUILD_CONTEXT=$(cd "$AGENTIC_MESH_RUNTIME_BUILD_CONTEXT" && pwd -P)
  if [ "$RESOLVED_WORKSPACE" = "$RESOLVED_SYSTEM" ]; then
    printf '%s\n' "Refusing to deploy: AGENTIC_MESH_WORKSPACE_HOST_PATH resolves to AGENTIC_MESH_SYSTEM_HOST_PATH." >&2
    printf '%s\n' "Set AGENTIC_MESH_WORKSPACE_HOST_PATH to a separate target repo, or set AGENTIC_MESH_ALLOW_WORKSPACE_EQUALS_SYSTEM=1 for an explicit local-dev override." >&2
    exit 1
  fi
  if [ "$RESOLVED_WORKSPACE" = "$RESOLVED_BUILD_CONTEXT" ]; then
    printf '%s\n' "Refusing to deploy: AGENTIC_MESH_RUNTIME_BUILD_CONTEXT resolves to AGENTIC_MESH_WORKSPACE_HOST_PATH." >&2
    printf '%s\n' "Build the runtime image from the clean system source checkout, not the mutable project target repo." >&2
    exit 1
  fi
  case "$RESOLVED_SYSTEM" in
    "$RESOLVED_WORKSPACE"/*)
      printf '%s\n' "Refusing to deploy: AGENTIC_MESH_SYSTEM_HOST_PATH is inside AGENTIC_MESH_WORKSPACE_HOST_PATH." >&2
      printf '%s\n' "Use the clean system checkout for /mesh/system so agent workspace edits cannot change the running control plane." >&2
      exit 1
      ;;
  esac
fi
export AGENTIC_MESH_WORKSPACE_HOST_PATH
export AGENTIC_MESH_URL_ROOT
export AGENTIC_MESH_RUNTIME_BUILD_CONTEXT
export AGENTIC_MESH_SYSTEM_HOST_PATH
export AGENTIC_MESH_PROJECT_HOST_PATH
export AGENTIC_MESH_DOCUMENTS_HOST_PATH
export AGENTIC_MESH_CODEX_HOME_HOST_PATH
export AGENTIC_MESH_OTEL_COLLECTOR_CONFIG_HOST_PATH
export AGENTIC_MESH_IMAGE_TAG
export AGENTIC_MESH_BASE_IMAGE_TAG
export AGENTIC_MESH_OPS_IMAGE_TAG
export AGENTIC_MESH_DEV_IMAGE_TAG
export AGENTIC_MESH_QA_IMAGE_TAG
export AGENTIC_MESH_ONEDRIVE_TOKEN
export AGENTIC_MESH_ONEDRIVE_DRIVE_ID
export AGENTIC_MESH_GRAPH_CLIENT_ID
export AGENTIC_MESH_GRAPH_TENANT_ID
export AGENTIC_MESH_GRAPH_REFRESH_TOKEN
export AGENTIC_MESH_GRAPH_SCOPES
export AGENTIC_MESH_SPONSOR_TEAMS_USER_ID
export AGENTIC_MESH_TEAMS_TOKEN
export AGENTIC_MESH_TEAMS_SENDER_USER_ID
export AGENTIC_MESH_TEAMS_PUBLIC_ENDPOINT
export AGENTIC_MESH_TEAMS_BOT_SERVICE_URL
export AGENTIC_MESH_TENANT_ID
export AGENTIC_MESH_PROJECT_TEAM_ID
export AGENTIC_MESH_PROJECT_CHANNEL_ID
export AGENTIC_MESH_SPONSOR_AAD_OBJECT_ID
export TEAMS_BOT_BUSINESS_ANALYST_APP_ID
export TEAMS_BOT_BUSINESS_ANALYST_SECRET
export TEAMS_BOT_DELIVERY_MANAGER_APP_ID
export TEAMS_BOT_DELIVERY_MANAGER_SECRET
export TEAMS_BOT_ENTERPRISE_ARCHITECT_APP_ID
export TEAMS_BOT_ENTERPRISE_ARCHITECT_SECRET
export TEAMS_BOT_PLATFORM_ENGINEER_APP_ID
export TEAMS_BOT_PLATFORM_ENGINEER_SECRET
export TEAMS_BOT_PRODUCT_MANAGER_APP_ID
export TEAMS_BOT_PRODUCT_MANAGER_SECRET
export TEAMS_BOT_PROMPT_ENGINEER_APP_ID
export TEAMS_BOT_PROMPT_ENGINEER_SECRET
export TEAMS_BOT_PROJECT_MANAGER_APP_ID
export TEAMS_BOT_PROJECT_MANAGER_SECRET
export TEAMS_BOT_RESEARCH_ANALYST_APP_ID
export TEAMS_BOT_RESEARCH_ANALYST_SECRET
export TEAMS_BOT_SECURITY_ARCHITECT_APP_ID
export TEAMS_BOT_SECURITY_ARCHITECT_SECRET
export TEAMS_BOT_SOLUTION_ARCHITECT_APP_ID
export TEAMS_BOT_SOLUTION_ARCHITECT_SECRET
export TEAMS_BOT_ENGINEERING_APP_ID
export TEAMS_BOT_ENGINEERING_SECRET
export TEAMS_BOT_QA_ENGINEER_APP_ID
export TEAMS_BOT_QA_ENGINEER_SECRET
export TEAMS_BOT_RELEASE_MANAGER_APP_ID
export TEAMS_BOT_RELEASE_MANAGER_SECRET
export TEAMS_BOT_TECHNICAL_WRITER_APP_ID
export TEAMS_BOT_TECHNICAL_WRITER_SECRET
export TEAMS_BOT_UX_DESIGNER_APP_ID
export TEAMS_BOT_UX_DESIGNER_SECRET
export AGENTIC_MESH_V4_STATUS_PORT
export AGENTIC_MESH_DATABASE_NAME
export AGENTIC_MESH_DATABASE_USER
export AGENTIC_MESH_DATABASE_HOST
export AGENTIC_MESH_DATABASE_PORT
export AGENTIC_MESH_POSTGRES_HOST_PORT
export AGENTIC_MESH_SOURCE_COMMIT
export AGENTIC_MESH_SOURCE_BRANCH
export AGENTIC_MESH_BUILD_TIME
export AGENTIC_MESH_BUILD_REF
export AGENTIC_MESH_ENVIRONMENT
export AGENTIC_MESH_LIFECYCLE_LOCK_PATH
export AGENTIC_MESH_LIFECYCLE_LOCK_TIMEOUT_SECONDS
export AGENTIC_MESH_LIFECYCLE_LOCK_STALE_SECONDS
export COMPOSE_PROJECT_NAME
export AGENTIC_MESH_LIFECYCLE_COMPOSE_PROJECT_NAME
export AGENTIC_MESH_LIFECYCLE_COMPOSE_PROFILES
export AGENTIC_MESH_LIFECYCLE_WORKING_DIRECTORY

mkdir -p "$STAGE_DIR"
cp "$COMPOSE_SRC/$COMPOSE_FILE_NAME" "$STAGE_DIR/docker-compose.yml"
cp "$COMPOSE_SRC/docker-compose.linuxch.yml" "$STAGE_DIR/docker-compose.linuxch.yml"
if grep -Eq "/mesh/(workspaces/agentic-mesh|project)/src" \
  "$STAGE_DIR/docker-compose.yml" "$STAGE_DIR/docker-compose.linuxch.yml"; then
  echo "Refusing to deploy: staged V4 compose points control-plane PYTHONPATH at a mutable project or workspace source tree." >&2
  echo "Regenerate compose from the system source before deploying." >&2
  exit 1
fi
cat > "$STAGE_DIR/.env" <<EOF
AGENTIC_MESH_WORKSPACE_HOST_PATH=$AGENTIC_MESH_WORKSPACE_HOST_PATH
AGENTIC_MESH_URL_ROOT=$AGENTIC_MESH_URL_ROOT
AGENTIC_MESH_RUNTIME_BUILD_CONTEXT=$AGENTIC_MESH_RUNTIME_BUILD_CONTEXT
AGENTIC_MESH_SYSTEM_HOST_PATH=$AGENTIC_MESH_SYSTEM_HOST_PATH
AGENTIC_MESH_PROJECT_HOST_PATH=$AGENTIC_MESH_PROJECT_HOST_PATH
AGENTIC_MESH_DOCUMENTS_HOST_PATH=$AGENTIC_MESH_DOCUMENTS_HOST_PATH
AGENTIC_MESH_CODEX_HOME_HOST_PATH=$AGENTIC_MESH_CODEX_HOME_HOST_PATH
AGENTIC_MESH_OTEL_COLLECTOR_CONFIG_HOST_PATH=$AGENTIC_MESH_OTEL_COLLECTOR_CONFIG_HOST_PATH
AGENTIC_MESH_IMAGE_TAG=$AGENTIC_MESH_IMAGE_TAG
AGENTIC_MESH_BASE_IMAGE_TAG=$AGENTIC_MESH_BASE_IMAGE_TAG
AGENTIC_MESH_OPS_IMAGE_TAG=$AGENTIC_MESH_OPS_IMAGE_TAG
AGENTIC_MESH_DEV_IMAGE_TAG=$AGENTIC_MESH_DEV_IMAGE_TAG
AGENTIC_MESH_QA_IMAGE_TAG=$AGENTIC_MESH_QA_IMAGE_TAG
AGENTIC_MESH_ONEDRIVE_TOKEN=$AGENTIC_MESH_ONEDRIVE_TOKEN
AGENTIC_MESH_ONEDRIVE_DRIVE_ID=$AGENTIC_MESH_ONEDRIVE_DRIVE_ID
AGENTIC_MESH_GRAPH_CLIENT_ID=$AGENTIC_MESH_GRAPH_CLIENT_ID
AGENTIC_MESH_GRAPH_TENANT_ID=$AGENTIC_MESH_GRAPH_TENANT_ID
AGENTIC_MESH_GRAPH_REFRESH_TOKEN=$AGENTIC_MESH_GRAPH_REFRESH_TOKEN
AGENTIC_MESH_GRAPH_SCOPES='$AGENTIC_MESH_GRAPH_SCOPES'
AGENTIC_MESH_SPONSOR_TEAMS_USER_ID=$AGENTIC_MESH_SPONSOR_TEAMS_USER_ID
AGENTIC_MESH_TEAMS_TOKEN=$AGENTIC_MESH_TEAMS_TOKEN
AGENTIC_MESH_TEAMS_SENDER_USER_ID=$AGENTIC_MESH_TEAMS_SENDER_USER_ID
AGENTIC_MESH_TEAMS_PUBLIC_ENDPOINT=$AGENTIC_MESH_TEAMS_PUBLIC_ENDPOINT
AGENTIC_MESH_TEAMS_BOT_SERVICE_URL=$AGENTIC_MESH_TEAMS_BOT_SERVICE_URL
AGENTIC_MESH_TENANT_ID=$AGENTIC_MESH_TENANT_ID
AGENTIC_MESH_PROJECT_TEAM_ID=$AGENTIC_MESH_PROJECT_TEAM_ID
AGENTIC_MESH_PROJECT_CHANNEL_ID=$AGENTIC_MESH_PROJECT_CHANNEL_ID
AGENTIC_MESH_SPONSOR_AAD_OBJECT_ID=$AGENTIC_MESH_SPONSOR_AAD_OBJECT_ID
TEAMS_BOT_BUSINESS_ANALYST_APP_ID=$TEAMS_BOT_BUSINESS_ANALYST_APP_ID
TEAMS_BOT_BUSINESS_ANALYST_SECRET=$TEAMS_BOT_BUSINESS_ANALYST_SECRET
TEAMS_BOT_DELIVERY_MANAGER_APP_ID=$TEAMS_BOT_DELIVERY_MANAGER_APP_ID
TEAMS_BOT_DELIVERY_MANAGER_SECRET=$TEAMS_BOT_DELIVERY_MANAGER_SECRET
TEAMS_BOT_ENTERPRISE_ARCHITECT_APP_ID=$TEAMS_BOT_ENTERPRISE_ARCHITECT_APP_ID
TEAMS_BOT_ENTERPRISE_ARCHITECT_SECRET=$TEAMS_BOT_ENTERPRISE_ARCHITECT_SECRET
TEAMS_BOT_PLATFORM_ENGINEER_APP_ID=$TEAMS_BOT_PLATFORM_ENGINEER_APP_ID
TEAMS_BOT_PLATFORM_ENGINEER_SECRET=$TEAMS_BOT_PLATFORM_ENGINEER_SECRET
TEAMS_BOT_PRODUCT_MANAGER_APP_ID=$TEAMS_BOT_PRODUCT_MANAGER_APP_ID
TEAMS_BOT_PRODUCT_MANAGER_SECRET=$TEAMS_BOT_PRODUCT_MANAGER_SECRET
TEAMS_BOT_PROMPT_ENGINEER_APP_ID=$TEAMS_BOT_PROMPT_ENGINEER_APP_ID
TEAMS_BOT_PROMPT_ENGINEER_SECRET=$TEAMS_BOT_PROMPT_ENGINEER_SECRET
TEAMS_BOT_PROJECT_MANAGER_APP_ID=$TEAMS_BOT_PROJECT_MANAGER_APP_ID
TEAMS_BOT_PROJECT_MANAGER_SECRET=$TEAMS_BOT_PROJECT_MANAGER_SECRET
TEAMS_BOT_RESEARCH_ANALYST_APP_ID=$TEAMS_BOT_RESEARCH_ANALYST_APP_ID
TEAMS_BOT_RESEARCH_ANALYST_SECRET=$TEAMS_BOT_RESEARCH_ANALYST_SECRET
TEAMS_BOT_SECURITY_ARCHITECT_APP_ID=$TEAMS_BOT_SECURITY_ARCHITECT_APP_ID
TEAMS_BOT_SECURITY_ARCHITECT_SECRET=$TEAMS_BOT_SECURITY_ARCHITECT_SECRET
TEAMS_BOT_SOLUTION_ARCHITECT_APP_ID=$TEAMS_BOT_SOLUTION_ARCHITECT_APP_ID
TEAMS_BOT_SOLUTION_ARCHITECT_SECRET=$TEAMS_BOT_SOLUTION_ARCHITECT_SECRET
TEAMS_BOT_ENGINEERING_APP_ID=$TEAMS_BOT_ENGINEERING_APP_ID
TEAMS_BOT_ENGINEERING_SECRET=$TEAMS_BOT_ENGINEERING_SECRET
TEAMS_BOT_QA_ENGINEER_APP_ID=$TEAMS_BOT_QA_ENGINEER_APP_ID
TEAMS_BOT_QA_ENGINEER_SECRET=$TEAMS_BOT_QA_ENGINEER_SECRET
TEAMS_BOT_RELEASE_MANAGER_APP_ID=$TEAMS_BOT_RELEASE_MANAGER_APP_ID
TEAMS_BOT_RELEASE_MANAGER_SECRET=$TEAMS_BOT_RELEASE_MANAGER_SECRET
TEAMS_BOT_TECHNICAL_WRITER_APP_ID=$TEAMS_BOT_TECHNICAL_WRITER_APP_ID
TEAMS_BOT_TECHNICAL_WRITER_SECRET=$TEAMS_BOT_TECHNICAL_WRITER_SECRET
TEAMS_BOT_UX_DESIGNER_APP_ID=$TEAMS_BOT_UX_DESIGNER_APP_ID
TEAMS_BOT_UX_DESIGNER_SECRET=$TEAMS_BOT_UX_DESIGNER_SECRET
AGENTIC_MESH_V4_STATUS_PORT=$AGENTIC_MESH_V4_STATUS_PORT
AGENTIC_MESH_DATABASE_NAME=$AGENTIC_MESH_DATABASE_NAME
AGENTIC_MESH_DATABASE_USER=$AGENTIC_MESH_DATABASE_USER
AGENTIC_MESH_DATABASE_HOST=$AGENTIC_MESH_DATABASE_HOST
AGENTIC_MESH_DATABASE_PORT=$AGENTIC_MESH_DATABASE_PORT
AGENTIC_MESH_POSTGRES_HOST_PORT=$AGENTIC_MESH_POSTGRES_HOST_PORT
AGENTIC_MESH_SOURCE_COMMIT=$AGENTIC_MESH_SOURCE_COMMIT
AGENTIC_MESH_SOURCE_BRANCH=$AGENTIC_MESH_SOURCE_BRANCH
AGENTIC_MESH_BUILD_TIME=$AGENTIC_MESH_BUILD_TIME
AGENTIC_MESH_BUILD_REF=$AGENTIC_MESH_BUILD_REF
AGENTIC_MESH_ENVIRONMENT=$AGENTIC_MESH_ENVIRONMENT
AGENTIC_MESH_LIFECYCLE_LOCK_PATH=/mesh/project/state/compose-lifecycle.lock
AGENTIC_MESH_LIFECYCLE_LOCK_TIMEOUT_SECONDS=$AGENTIC_MESH_LIFECYCLE_LOCK_TIMEOUT_SECONDS
AGENTIC_MESH_LIFECYCLE_LOCK_STALE_SECONDS=$AGENTIC_MESH_LIFECYCLE_LOCK_STALE_SECONDS
COMPOSE_PROJECT_NAME=$COMPOSE_PROJECT_NAME
AGENTIC_MESH_LIFECYCLE_COMPOSE_PROJECT_NAME=$AGENTIC_MESH_LIFECYCLE_COMPOSE_PROJECT_NAME
AGENTIC_MESH_LIFECYCLE_COMPOSE_PROFILES=$AGENTIC_MESH_LIFECYCLE_COMPOSE_PROFILES
AGENTIC_MESH_LIFECYCLE_WORKING_DIRECTORY=$AGENTIC_MESH_LIFECYCLE_WORKING_DIRECTORY
EOF
chmod 600 "$STAGE_DIR/.env"

validate_effective_compose() {
  compose_bin=$1
  shift
  if "$compose_bin" "$@" config | grep -Eq "PYTHONPATH:.*/mesh/(workspaces/agentic-mesh|project)/src"; then
    echo "Refusing to deploy: effective V4 compose points control-plane PYTHONPATH at a mutable project or workspace source tree." >&2
    echo "Regenerate compose from the system source and remove PYTHONPATH overrides from deployment env." >&2
    exit 1
  fi
}

if [ "$#" -eq 0 ]; then
  set -- up -d
fi

acquire_lifecycle_lock() {
  if [ "${AGENTIC_MESH_LIFECYCLE_LOCK_HELD:-0}" = "1" ]; then
    return 0
  fi
  mkdir -p "$(dirname "$AGENTIC_MESH_LIFECYCLE_LOCK_PATH")"
  lock_started_at=$(date +%s)
  while ! mkdir "$AGENTIC_MESH_LIFECYCLE_LOCK_PATH" 2>/tmp/agentic-mesh-lifecycle-lock.err; do
    if [ ! -e "$AGENTIC_MESH_LIFECYCLE_LOCK_PATH" ]; then
      echo "Unable to create lifecycle lock at $AGENTIC_MESH_LIFECYCLE_LOCK_PATH:" >&2
      cat /tmp/agentic-mesh-lifecycle-lock.err >&2
      exit 1
    fi
    now=$(date +%s)
    lock_age=$((now - $(stat -c %Y "$AGENTIC_MESH_LIFECYCLE_LOCK_PATH" 2>/dev/null || echo "$now")))
    if [ "$lock_age" -ge "$AGENTIC_MESH_LIFECYCLE_LOCK_STALE_SECONDS" ]; then
      rm -rf "$AGENTIC_MESH_LIFECYCLE_LOCK_PATH"
      continue
    fi
    if [ $((now - lock_started_at)) -ge "$AGENTIC_MESH_LIFECYCLE_LOCK_TIMEOUT_SECONDS" ]; then
      echo "Timed out waiting for lifecycle lock: $AGENTIC_MESH_LIFECYCLE_LOCK_PATH" >&2
      exit 1
    fi
    sleep 1
  done
  printf '%s\n' "$$" > "$AGENTIC_MESH_LIFECYCLE_LOCK_PATH/owner"
  AGENTIC_MESH_LIFECYCLE_LOCK_ACQUIRED=1
}

release_lifecycle_lock() {
  if [ "${AGENTIC_MESH_LIFECYCLE_LOCK_ACQUIRED:-0}" = "1" ]; then
    rm -rf "$AGENTIC_MESH_LIFECYCLE_LOCK_PATH"
  fi
}

run_compose() {
  acquire_lifecycle_lock
  trap release_lifecycle_lock EXIT INT TERM
  "$@"
}

if docker compose version >/dev/null 2>&1; then
  validate_effective_compose docker \
    compose \
    --env-file "$STAGE_DIR/.env" \
    -f "$STAGE_DIR/docker-compose.yml" \
    -f "$STAGE_DIR/docker-compose.linuxch.yml"
  run_compose docker compose \
    --env-file "$STAGE_DIR/.env" \
    -f "$STAGE_DIR/docker-compose.yml" \
    -f "$STAGE_DIR/docker-compose.linuxch.yml" \
    "$@"
  exit $?
fi

if command -v docker-compose >/dev/null 2>&1; then
  validate_effective_compose docker-compose \
    --env-file "$STAGE_DIR/.env" \
    -f "$STAGE_DIR/docker-compose.yml" \
    -f "$STAGE_DIR/docker-compose.linuxch.yml"
  run_compose docker-compose \
    --env-file "$STAGE_DIR/.env" \
    -f "$STAGE_DIR/docker-compose.yml" \
    -f "$STAGE_DIR/docker-compose.linuxch.yml" \
    "$@"
  exit $?
fi

echo "Docker Compose CLI is required for linuxch deployment." >&2
exit 127
