#!/bin/sh
set -eu

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
REPO_ROOT=$(CDPATH= cd -- "$SCRIPT_DIR/.." && pwd)
COMPOSE_SRC="$REPO_ROOT/examples/projects/agentic-mesh-dev/deploy/compose"
STAGE_DIR="${AGENTIC_MESH_COMPOSE_STAGE_DIR:-$HOME/agentic-mesh-compose-run}"

if [ -f "$COMPOSE_SRC/.env" ]; then
  set -a
  # shellcheck disable=SC1091
  . "$COMPOSE_SRC/.env"
  set +a
fi

AGENTIC_MESH_WORKSPACE_HOST_PATH="${AGENTIC_MESH_WORKSPACE_HOST_PATH:-$REPO_ROOT}"
AGENTIC_MESH_URL_ROOT="${AGENTIC_MESH_URL_ROOT:-http://linuxch:8100}"
AGENTIC_MESH_RUNTIME_BUILD_CONTEXT="${AGENTIC_MESH_RUNTIME_BUILD_CONTEXT:-$REPO_ROOT}"
AGENTIC_MESH_SYSTEM_HOST_PATH="${AGENTIC_MESH_SYSTEM_HOST_PATH:-$REPO_ROOT}"
AGENTIC_MESH_PROJECT_HOST_PATH="${AGENTIC_MESH_PROJECT_HOST_PATH:-$REPO_ROOT/examples/projects/agentic-mesh-dev}"
AGENTIC_MESH_CODEX_HOME_HOST_PATH="${AGENTIC_MESH_CODEX_HOME_HOST_PATH:-$AGENTIC_MESH_PROJECT_HOST_PATH/state/worker_mounts/codex-agentic-mesh-dev-team-home-q}"
AGENTIC_MESH_OTEL_COLLECTOR_CONFIG_HOST_PATH="${AGENTIC_MESH_OTEL_COLLECTOR_CONFIG_HOST_PATH:-$REPO_ROOT/config/otel/collector.yaml}"
AGENTIC_MESH_IMAGE_TAG="${AGENTIC_MESH_IMAGE_TAG:-agentic-mesh:local}"
AGENTIC_MESH_ONEDRIVE_TOKEN="${AGENTIC_MESH_ONEDRIVE_TOKEN:-}"
AGENTIC_MESH_ONEDRIVE_DRIVE_ID="${AGENTIC_MESH_ONEDRIVE_DRIVE_ID:-}"
AGENTIC_MESH_SPONSOR_TEAMS_USER_ID="${AGENTIC_MESH_SPONSOR_TEAMS_USER_ID:-}"
AGENTIC_MESH_TEAMS_TOKEN="${AGENTIC_MESH_TEAMS_TOKEN:-}"
AGENTIC_MESH_TEAMS_SENDER_USER_ID="${AGENTIC_MESH_TEAMS_SENDER_USER_ID:-}"
AGENTIC_MESH_TEAMS_BOT_SERVICE_URL="${AGENTIC_MESH_TEAMS_BOT_SERVICE_URL:-}"
AGENTIC_MESH_TENANT_ID="${AGENTIC_MESH_TENANT_ID:-}"
TEAMS_BOT_BUSINESS_ANALYST_APP_ID="${TEAMS_BOT_BUSINESS_ANALYST_APP_ID:-}"
TEAMS_BOT_BUSINESS_ANALYST_SECRET="${TEAMS_BOT_BUSINESS_ANALYST_SECRET:-}"
TEAMS_BOT_DELIVERY_MANAGER_APP_ID="${TEAMS_BOT_DELIVERY_MANAGER_APP_ID:-}"
TEAMS_BOT_DELIVERY_MANAGER_SECRET="${TEAMS_BOT_DELIVERY_MANAGER_SECRET:-}"
TEAMS_BOT_ENTERPRISE_ARCHITECT_APP_ID="${TEAMS_BOT_ENTERPRISE_ARCHITECT_APP_ID:-}"
TEAMS_BOT_ENTERPRISE_ARCHITECT_SECRET="${TEAMS_BOT_ENTERPRISE_ARCHITECT_SECRET:-}"
TEAMS_BOT_PLATFORM_ENGINEER_APP_ID="${TEAMS_BOT_PLATFORM_ENGINEER_APP_ID:-}"
TEAMS_BOT_PLATFORM_ENGINEER_SECRET="${TEAMS_BOT_PLATFORM_ENGINEER_SECRET:-}"
TEAMS_BOT_PRODUCT_MANAGER_APP_ID="${TEAMS_BOT_PRODUCT_MANAGER_APP_ID:-}"
TEAMS_BOT_PRODUCT_MANAGER_SECRET="${TEAMS_BOT_PRODUCT_MANAGER_SECRET:-}"
TEAMS_BOT_PROMPT_ENGINEER_APP_ID="${TEAMS_BOT_PROMPT_ENGINEER_APP_ID:-}"
TEAMS_BOT_PROMPT_ENGINEER_SECRET="${TEAMS_BOT_PROMPT_ENGINEER_SECRET:-}"
TEAMS_BOT_PROJECT_MANAGER_APP_ID="${TEAMS_BOT_PROJECT_MANAGER_APP_ID:-}"
TEAMS_BOT_PROJECT_MANAGER_SECRET="${TEAMS_BOT_PROJECT_MANAGER_SECRET:-}"
TEAMS_BOT_RESEARCH_ANALYST_APP_ID="${TEAMS_BOT_RESEARCH_ANALYST_APP_ID:-}"
TEAMS_BOT_RESEARCH_ANALYST_SECRET="${TEAMS_BOT_RESEARCH_ANALYST_SECRET:-}"
TEAMS_BOT_SECURITY_ARCHITECT_APP_ID="${TEAMS_BOT_SECURITY_ARCHITECT_APP_ID:-}"
TEAMS_BOT_SECURITY_ARCHITECT_SECRET="${TEAMS_BOT_SECURITY_ARCHITECT_SECRET:-}"
TEAMS_BOT_SOLUTION_ARCHITECT_APP_ID="${TEAMS_BOT_SOLUTION_ARCHITECT_APP_ID:-}"
TEAMS_BOT_SOLUTION_ARCHITECT_SECRET="${TEAMS_BOT_SOLUTION_ARCHITECT_SECRET:-}"
TEAMS_BOT_ENGINEERING_APP_ID="${TEAMS_BOT_ENGINEERING_APP_ID:-}"
TEAMS_BOT_ENGINEERING_SECRET="${TEAMS_BOT_ENGINEERING_SECRET:-}"
TEAMS_BOT_QA_ENGINEER_APP_ID="${TEAMS_BOT_QA_ENGINEER_APP_ID:-}"
TEAMS_BOT_QA_ENGINEER_SECRET="${TEAMS_BOT_QA_ENGINEER_SECRET:-}"
TEAMS_BOT_RELEASE_MANAGER_APP_ID="${TEAMS_BOT_RELEASE_MANAGER_APP_ID:-}"
TEAMS_BOT_RELEASE_MANAGER_SECRET="${TEAMS_BOT_RELEASE_MANAGER_SECRET:-}"
TEAMS_BOT_TECHNICAL_WRITER_APP_ID="${TEAMS_BOT_TECHNICAL_WRITER_APP_ID:-}"
TEAMS_BOT_TECHNICAL_WRITER_SECRET="${TEAMS_BOT_TECHNICAL_WRITER_SECRET:-}"
TEAMS_BOT_UX_DESIGNER_APP_ID="${TEAMS_BOT_UX_DESIGNER_APP_ID:-}"
TEAMS_BOT_UX_DESIGNER_SECRET="${TEAMS_BOT_UX_DESIGNER_SECRET:-}"
AGENTIC_MESH_V3_STATUS_PORT="${AGENTIC_MESH_V3_STATUS_PORT:-8100}"
if [ -n "${AGENTIC_MESH_FORCE_V3_STATUS_PORT:-}" ]; then
  AGENTIC_MESH_V3_STATUS_PORT="$AGENTIC_MESH_FORCE_V3_STATUS_PORT"
fi
AGENTIC_MESH_NATS_STATE_HOST_PATH="${AGENTIC_MESH_NATS_STATE_HOST_PATH:-$AGENTIC_MESH_PROJECT_HOST_PATH/state/v3/nats}"
AGENTIC_MESH_SOURCE_COMMIT="${AGENTIC_MESH_SOURCE_COMMIT:-$(git -C "$REPO_ROOT" rev-parse --short=12 HEAD 2>/dev/null || printf 'unknown')}"
AGENTIC_MESH_SOURCE_BRANCH="${AGENTIC_MESH_SOURCE_BRANCH:-$(git -C "$REPO_ROOT" symbolic-ref --quiet --short HEAD 2>/dev/null || printf 'detached')}"
AGENTIC_MESH_BUILD_TIME="${AGENTIC_MESH_BUILD_TIME:-$(date -u '+%Y-%m-%dT%H:%M:%SZ')}"
AGENTIC_MESH_BUILD_REF="${AGENTIC_MESH_BUILD_REF:-$AGENTIC_MESH_SOURCE_BRANCH@$AGENTIC_MESH_SOURCE_COMMIT}"
AGENTIC_MESH_ENVIRONMENT="${AGENTIC_MESH_ENVIRONMENT:-dogfood}"
COMPOSE_PROJECT_NAME="${COMPOSE_PROJECT_NAME:-agentic-mesh}"
export AGENTIC_MESH_WORKSPACE_HOST_PATH
export AGENTIC_MESH_URL_ROOT
export AGENTIC_MESH_RUNTIME_BUILD_CONTEXT
export AGENTIC_MESH_SYSTEM_HOST_PATH
export AGENTIC_MESH_PROJECT_HOST_PATH
export AGENTIC_MESH_CODEX_HOME_HOST_PATH
export AGENTIC_MESH_OTEL_COLLECTOR_CONFIG_HOST_PATH
export AGENTIC_MESH_IMAGE_TAG
export AGENTIC_MESH_ONEDRIVE_TOKEN
export AGENTIC_MESH_ONEDRIVE_DRIVE_ID
export AGENTIC_MESH_SPONSOR_TEAMS_USER_ID
export AGENTIC_MESH_TEAMS_TOKEN
export AGENTIC_MESH_TEAMS_SENDER_USER_ID
export AGENTIC_MESH_TEAMS_BOT_SERVICE_URL
export AGENTIC_MESH_TENANT_ID
export TEAMS_BOT_BUSINESS_ANALYST_APP_ID
export TEAMS_BOT_BUSINESS_ANALYST_SECRET
export TEAMS_BOT_DELIVERY_MANAGER_APP_ID
export TEAMS_BOT_DELIVERY_MANAGER_SECRET
export TEAMS_BOT_ENTERPRISE_ARCHITECT_APP_ID
export TEAMS_BOT_ENTERPRISE_ARCHITECT_SECRET
export TEAMS_BOT_PLATFORM_ENGINEER_APP_ID
export TEAMS_BOT_PLATFORM_ENGINEER_SECRET
export TEAMS_BOT_PRODUCT_MANAGER_APP_ID
export TEAMS_BOT_PRODUCT_MANAGER_SECRET
export TEAMS_BOT_PROMPT_ENGINEER_APP_ID
export TEAMS_BOT_PROMPT_ENGINEER_SECRET
export TEAMS_BOT_PROJECT_MANAGER_APP_ID
export TEAMS_BOT_PROJECT_MANAGER_SECRET
export TEAMS_BOT_RESEARCH_ANALYST_APP_ID
export TEAMS_BOT_RESEARCH_ANALYST_SECRET
export TEAMS_BOT_SECURITY_ARCHITECT_APP_ID
export TEAMS_BOT_SECURITY_ARCHITECT_SECRET
export TEAMS_BOT_SOLUTION_ARCHITECT_APP_ID
export TEAMS_BOT_SOLUTION_ARCHITECT_SECRET
export TEAMS_BOT_ENGINEERING_APP_ID
export TEAMS_BOT_ENGINEERING_SECRET
export TEAMS_BOT_QA_ENGINEER_APP_ID
export TEAMS_BOT_QA_ENGINEER_SECRET
export TEAMS_BOT_RELEASE_MANAGER_APP_ID
export TEAMS_BOT_RELEASE_MANAGER_SECRET
export TEAMS_BOT_TECHNICAL_WRITER_APP_ID
export TEAMS_BOT_TECHNICAL_WRITER_SECRET
export TEAMS_BOT_UX_DESIGNER_APP_ID
export TEAMS_BOT_UX_DESIGNER_SECRET
export AGENTIC_MESH_V3_STATUS_PORT
export AGENTIC_MESH_NATS_STATE_HOST_PATH
export AGENTIC_MESH_SOURCE_COMMIT
export AGENTIC_MESH_SOURCE_BRANCH
export AGENTIC_MESH_BUILD_TIME
export AGENTIC_MESH_BUILD_REF
export AGENTIC_MESH_ENVIRONMENT
export COMPOSE_PROJECT_NAME

mkdir -p "$STAGE_DIR"
cp "$COMPOSE_SRC/docker-compose.yml" "$STAGE_DIR/docker-compose.yml"
cp "$COMPOSE_SRC/docker-compose.linuxch.yml" "$STAGE_DIR/docker-compose.linuxch.yml"
cat > "$STAGE_DIR/.env" <<EOF
AGENTIC_MESH_WORKSPACE_HOST_PATH=$AGENTIC_MESH_WORKSPACE_HOST_PATH
AGENTIC_MESH_URL_ROOT=$AGENTIC_MESH_URL_ROOT
AGENTIC_MESH_RUNTIME_BUILD_CONTEXT=$AGENTIC_MESH_RUNTIME_BUILD_CONTEXT
AGENTIC_MESH_SYSTEM_HOST_PATH=$AGENTIC_MESH_SYSTEM_HOST_PATH
AGENTIC_MESH_PROJECT_HOST_PATH=$AGENTIC_MESH_PROJECT_HOST_PATH
AGENTIC_MESH_CODEX_HOME_HOST_PATH=$AGENTIC_MESH_CODEX_HOME_HOST_PATH
AGENTIC_MESH_OTEL_COLLECTOR_CONFIG_HOST_PATH=$AGENTIC_MESH_OTEL_COLLECTOR_CONFIG_HOST_PATH
AGENTIC_MESH_IMAGE_TAG=$AGENTIC_MESH_IMAGE_TAG
AGENTIC_MESH_ONEDRIVE_TOKEN=$AGENTIC_MESH_ONEDRIVE_TOKEN
AGENTIC_MESH_ONEDRIVE_DRIVE_ID=$AGENTIC_MESH_ONEDRIVE_DRIVE_ID
AGENTIC_MESH_SPONSOR_TEAMS_USER_ID=$AGENTIC_MESH_SPONSOR_TEAMS_USER_ID
AGENTIC_MESH_TEAMS_TOKEN=$AGENTIC_MESH_TEAMS_TOKEN
AGENTIC_MESH_TEAMS_SENDER_USER_ID=$AGENTIC_MESH_TEAMS_SENDER_USER_ID
AGENTIC_MESH_TEAMS_BOT_SERVICE_URL=$AGENTIC_MESH_TEAMS_BOT_SERVICE_URL
AGENTIC_MESH_TENANT_ID=$AGENTIC_MESH_TENANT_ID
TEAMS_BOT_BUSINESS_ANALYST_APP_ID=$TEAMS_BOT_BUSINESS_ANALYST_APP_ID
TEAMS_BOT_BUSINESS_ANALYST_SECRET=$TEAMS_BOT_BUSINESS_ANALYST_SECRET
TEAMS_BOT_DELIVERY_MANAGER_APP_ID=$TEAMS_BOT_DELIVERY_MANAGER_APP_ID
TEAMS_BOT_DELIVERY_MANAGER_SECRET=$TEAMS_BOT_DELIVERY_MANAGER_SECRET
TEAMS_BOT_ENTERPRISE_ARCHITECT_APP_ID=$TEAMS_BOT_ENTERPRISE_ARCHITECT_APP_ID
TEAMS_BOT_ENTERPRISE_ARCHITECT_SECRET=$TEAMS_BOT_ENTERPRISE_ARCHITECT_SECRET
TEAMS_BOT_PLATFORM_ENGINEER_APP_ID=$TEAMS_BOT_PLATFORM_ENGINEER_APP_ID
TEAMS_BOT_PLATFORM_ENGINEER_SECRET=$TEAMS_BOT_PLATFORM_ENGINEER_SECRET
TEAMS_BOT_PRODUCT_MANAGER_APP_ID=$TEAMS_BOT_PRODUCT_MANAGER_APP_ID
TEAMS_BOT_PRODUCT_MANAGER_SECRET=$TEAMS_BOT_PRODUCT_MANAGER_SECRET
TEAMS_BOT_PROMPT_ENGINEER_APP_ID=$TEAMS_BOT_PROMPT_ENGINEER_APP_ID
TEAMS_BOT_PROMPT_ENGINEER_SECRET=$TEAMS_BOT_PROMPT_ENGINEER_SECRET
TEAMS_BOT_PROJECT_MANAGER_APP_ID=$TEAMS_BOT_PROJECT_MANAGER_APP_ID
TEAMS_BOT_PROJECT_MANAGER_SECRET=$TEAMS_BOT_PROJECT_MANAGER_SECRET
TEAMS_BOT_RESEARCH_ANALYST_APP_ID=$TEAMS_BOT_RESEARCH_ANALYST_APP_ID
TEAMS_BOT_RESEARCH_ANALYST_SECRET=$TEAMS_BOT_RESEARCH_ANALYST_SECRET
TEAMS_BOT_SECURITY_ARCHITECT_APP_ID=$TEAMS_BOT_SECURITY_ARCHITECT_APP_ID
TEAMS_BOT_SECURITY_ARCHITECT_SECRET=$TEAMS_BOT_SECURITY_ARCHITECT_SECRET
TEAMS_BOT_SOLUTION_ARCHITECT_APP_ID=$TEAMS_BOT_SOLUTION_ARCHITECT_APP_ID
TEAMS_BOT_SOLUTION_ARCHITECT_SECRET=$TEAMS_BOT_SOLUTION_ARCHITECT_SECRET
TEAMS_BOT_ENGINEERING_APP_ID=$TEAMS_BOT_ENGINEERING_APP_ID
TEAMS_BOT_ENGINEERING_SECRET=$TEAMS_BOT_ENGINEERING_SECRET
TEAMS_BOT_QA_ENGINEER_APP_ID=$TEAMS_BOT_QA_ENGINEER_APP_ID
TEAMS_BOT_QA_ENGINEER_SECRET=$TEAMS_BOT_QA_ENGINEER_SECRET
TEAMS_BOT_RELEASE_MANAGER_APP_ID=$TEAMS_BOT_RELEASE_MANAGER_APP_ID
TEAMS_BOT_RELEASE_MANAGER_SECRET=$TEAMS_BOT_RELEASE_MANAGER_SECRET
TEAMS_BOT_TECHNICAL_WRITER_APP_ID=$TEAMS_BOT_TECHNICAL_WRITER_APP_ID
TEAMS_BOT_TECHNICAL_WRITER_SECRET=$TEAMS_BOT_TECHNICAL_WRITER_SECRET
TEAMS_BOT_UX_DESIGNER_APP_ID=$TEAMS_BOT_UX_DESIGNER_APP_ID
TEAMS_BOT_UX_DESIGNER_SECRET=$TEAMS_BOT_UX_DESIGNER_SECRET
AGENTIC_MESH_V3_STATUS_PORT=$AGENTIC_MESH_V3_STATUS_PORT
AGENTIC_MESH_NATS_STATE_HOST_PATH=$AGENTIC_MESH_NATS_STATE_HOST_PATH
AGENTIC_MESH_SOURCE_COMMIT=$AGENTIC_MESH_SOURCE_COMMIT
AGENTIC_MESH_SOURCE_BRANCH=$AGENTIC_MESH_SOURCE_BRANCH
AGENTIC_MESH_BUILD_TIME=$AGENTIC_MESH_BUILD_TIME
AGENTIC_MESH_BUILD_REF=$AGENTIC_MESH_BUILD_REF
AGENTIC_MESH_ENVIRONMENT=$AGENTIC_MESH_ENVIRONMENT
COMPOSE_PROJECT_NAME=$COMPOSE_PROJECT_NAME
EOF
chmod 600 "$STAGE_DIR/.env"

if [ "$#" -eq 0 ]; then
  set -- up -d
fi

if docker compose version >/dev/null 2>&1; then
  exec docker compose \
    --env-file "$STAGE_DIR/.env" \
    -f "$STAGE_DIR/docker-compose.yml" \
    -f "$STAGE_DIR/docker-compose.linuxch.yml" \
    "$@"
fi

if command -v docker-compose >/dev/null 2>&1; then
  exec docker-compose \
    --env-file "$STAGE_DIR/.env" \
    -f "$STAGE_DIR/docker-compose.yml" \
    -f "$STAGE_DIR/docker-compose.linuxch.yml" \
    "$@"
fi

echo "Docker Compose CLI is required for linuxch deployment." >&2
exit 127
